import { SpecialParameter } from "src/models/biomarker.model";

export const sleepParameters: SpecialParameter[] = [
  { id: 'sleep_period_id', name_long: 'Period id', unit: '{count}' },
  { id: 'sleep_is_longest', name_long: 'Is longest', unit: '{bool}' },
  { id: 'sleep_bedtime', name_long: 'Total Bedtime', unit: 's' },
  { id: 'sleep_bedtime_start', name_long: 'Bedtime Start', unit: '{TmStp}' },
  { id: 'sleep_bedtime_end', name_long: 'Bedtime End', unit: '{TmStp}' },
  { id: 'sleep_score', name_long: 'Sleep Score', unit: '{score}' },
  { id: 'sleep_score_total', name_long: 'Total Sleep Time Score', unit: '{score}' },
  { id: 'sleep_score_disturbances', name_long: 'Sleep Disturbances Score', unit: '{score}' },
  { id: 'sleep_score_efficiency', name_long: 'Sleep Efficiency Score', unit: '{score}' },
  { id: 'sleep_score_latency', name_long: 'Sleep Latency Score', unit: '{score}' },
  { id: 'sleep_score_rem', name_long: 'REM Sleep Score', unit: '{score}' },
  { id: 'sleep_score_deep', name_long: 'Deep Sleep Score', unit: '{score}' },
  { id: 'sleep_score_alignment', name_long: 'Sleep Timing Score', unit: '{score}' },
  { id: 'sleep_efficiency', name_long: 'Sleep Efficiency', unit: '{score}' },
  { id: 'sleep_restless', name_long: 'Restless Sleep Time Percentage', unit: '%' },
  { id: 'sleep_time_total', name_long: 'Total Sleep Time', unit: 's' },
  { id: 'sleep_time_awake', name_long: 'Awake Time', unit: 's' },
  { id: 'sleep_time_light', name_long: 'Light Sleep Time', unit: 's' },
  { id: 'sleep_time_rem', name_long: 'REM Sleep Time', unit: 's' },
  { id: 'sleep_time_deep', name_long: 'Deep Sleep Time', unit: 's' },
  { id: 'sleep_onset_latency', name_long: 'Sleep Latency', unit: 's' },
  { id: 'sleep_midpoint_time', name_long: 'Midpoint Time', unit: 's' },
  { id: 'sleep_respiratory_rate', name_long: 'Respiratory Rate', unit: '{breaths}/min' },
  { id: 'sleep_temperature_delta', name_long: 'Temperature Deviation (°C)', unit: 'Cel' },
  { id: 'sleep_heart_rate_min', name_long: 'Lowest Resting Heart Rate', unit: '{beats}/min' },
  { id: 'sleep_heart_rate', name_long: 'Average Resting Heart Rate', unit: '{beats}/min' },
  { id: 'sleep_heart_rate_variability', name_long: 'Average HRV', unit: 'ms' },
  { id: 'sleep_nap_count', name_long: 'Nap counts per day', unit: '{count}' },
  { id: 'sleep_nap_time', name_long: 'Total Nap sleep time', unit: '' },
  { id: 'sleep_latency_arising', name_long: 'Latency to arising', unit: 's' },
  { id: 'sleep_cycles', name_long: 'Number of Sleep Cycles', unit: '{count}' },
  { id: 'sleep_awakenings', name_long: 'Number of awakenings', unit: '{count}' },
  { id: 'sleep_disturbances', name_long: 'Disturbances count', unit: '{count}' },
  { id: 'sleep_awake', name_long: 'Awake Time Percentage', unit: '%' },
  { id: 'sleep_light', name_long: 'Light Sleep Time Percentage', unit: '%' },
  { id: 'sleep_rem', name_long: 'REM Sleep Time Percentage', unit: '%' },
  { id: 'sleep_deep', name_long: 'Deep Sleep Time Percentage', unit: '%' },
  { id: 'sleep_time_restless', name_long: 'Restless Sleep Time', unit: 's' },
  { id: 'sleep_hypnogram_5min', name_long: 'Hypnogram 5min', unit: '{string}' },
  { id: 'sleep_hr_5min', name_long: 'Heart rate 5min', unit: '{beats}/min' },
  { id: 'sleep_rmssd_5min', name_long: 'Heart rate variability (Rmssd) 5min', unit: 'ms' },
  { id: 'snoring_score', name_long: 'Snoring score', unit: '{score}' },
  { id: 'snoring_time', name_long: 'Snoring time', unit: 's' },
  { id: 'snoring_volume', name_long: 'Snoring volume', unit: 'dB' },
  { id: 'snoring_volume_max', name_long: 'Snoring volume highest', unit: 'dB' },
  { id: 'snoring_quiet', name_long: 'Snoring time quiet percentage', unit: '%' },
  { id: 'snoring_light', name_long: 'Snoring time light percentage', unit: '%' },
  { id: 'snoring_loud', name_long: 'Snoring time loud percentage', unit: '%' },
  { id: 'snoring_epic', name_long: 'Snoring time epic percentage', unit: '%' },
];